In [71]:
import glob
import json
import os
import numpy as np
files = glob.glob("log/*.json")
import pandas as pd
myScore=[]
precision_0 = []
precision_1 = []
cv_score = []
roc = []
name = []
for f in files:
    with open(f) as json_file:
        data = json.load(json_file)
        
        #print(f, "\r")
        roc.append(data["roc"])
        
        myScore.append(data["myScore"])
        precision_0.append(data["report"]["0"]["precision"])

        precision_1.append(data["report"]["1"]["precision"])
        cv_score.append(data["cv_score"])
        
        name.append(os.path.basename(f).split(".")[0])


In [72]:
myScore=np.array(myScore)
precision_0 = np.array(precision_0)
precision_1 = np.array(precision_1)
cv_score =np.array(cv_score)
roc = np.array(roc)
name = np.array(name)
print(myScore.argmax())
print(precision_0.argmax())
print(precision_1.argmax())
print(cv_score.argmax())
print(roc.argmax())

96
95
106
14
96


In [73]:
precision = []
for i in range(len(myScore)):
    precision.append(1*85*precision_0[i]+9*15*precision_1[i])
precision = np.array(precision) 
precision = precision/precision.max()

In [74]:
result = np.argsort(precision)[::-1]
result

array([106, 105,  14,  19,  25,  96,  95,  99,  94,  76,  51, 100,  75,
        68,  78,  65, 111,  58,  60,  46,  74,  36,  80,  40,  63, 110,
        72,  45,  48,  66,  44,  57,  81,  52,  69,  77,  62,  49, 109,
        71,  67,  70,  56,  61,  47,  64,  93,  31,  23,  91,  42,  32,
        54,  37,  30,  73,  35,  55,  50,  53,  79,  59,  21,   0,   1,
        34,  27, 108,   6,  29,  15,  17,  13,  41,  38,   7,  22,  20,
        83,  26,  28,  43,  84,  39, 101,   2,   3, 104, 103, 102,  12,
        33, 107,   9,  10,  85,  86,  88,  87,  90,  18,  82,  89,  97,
        24,  92,   8,  98,   5,  16,   4,  11], dtype=int64)

In [57]:
i=96
print(name[i])
print(cv_score[i])
print(roc[i])


rf-9286
0.7797142857142857
0.9115673772363914


In [23]:
result = np.argsort(roc)[::-1]
result

array([ 96,  95, 111,  80,  78,  76,  77,  69,  79,  94,  75,  74,  68,
        72,  70,  71,  65,  23, 110,  66,  67,  73,  63,  60,  58,  64,
        62,  51,  61, 109,  57,  81,  99, 100,  56,  59,  52,  54,  46,
        48,  55,  45,  49,  53,  44,  47,  40,  36,  50,  42,  93,  37,
        35,  91,  38,  25,  32,  43,  31,  30,  39,  34,  19, 104,  29,
       103, 108,  27,  28,  26,  12,  33,   6,   1,  41,  21,  22,  20,
         7,   0,  14,  17,  92,  90,  15,   3,  84,  88,  86,  83,  89,
        87, 101,  85,  10,  24, 102,  18,   2,   9,  13, 106,  97, 107,
        98,  82,  16,   8,   5,   4, 105,  11], dtype=int64)

In [ ]:
StackingClassifier

In [12]:
name[78]

'lgbm-7780'

In [7]:
np.argsort(myScore)[::-1]

array([ 95,  94, 108,  79,  78,  77,  69,  76,  75,  74,  93,  23,  72,
        71,  70,  73,  68,  67, 107,  66,  65,  64,  63,  62,  61,  60,
        59,  58, 106,  57,  80,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42, 101,  40,  39,  38,  37,  36,
       100,  35,  92,  91,  90,  34,  33,  12,  32,  31,  30,  29,  28,
        26,  27, 105,  89,  25,  24,  88,   6,  41,  22,  87,   1,  86,
        85,  21,  20,  84,  19,  97,   7,  10,  18,  17,   0,   3,  16,
        96,  83,  15,  99,   9,  98,  82,   5,  81,   8,   2, 104,  14,
        13,   4, 103, 102,  11], dtype=int64)

In [30]:
x = np.where(myScore == myScore.max())
name[x]

array(['rf-9286'], dtype='<U10')

In [105]:
cv_score = np.array(cv_score)

cv_score.max()

0.8787142857142858

In [106]:
cv_score.argmax()

3

In [109]:
print( precision_0[3], precision_1[3] )

0.9237427864798021 0.6315508021390375


In [115]:
name[68]

'xgb-8156'

In [127]:
df_analysis = pd.read_csv("analysis.csv").to_numpy()
final_score = []
final_name = []
for f in df_analysis:
    _name = f[0].split(".")[0]
    final_name.append(_name)
    final_score.append(f[1])
final_score = np.array(final_score)
final_name = np.array(final_name)
result = np.argsort(final_score)[::-1]
result

array([ 0, 52,  8, 25, 62, 49, 45, 53, 43, 51,  7, 46, 30,  6, 57, 26,  4,
       48, 29, 50,  5, 24, 68, 47, 56,  3, 40, 15, 66, 17, 38, 59,  2, 65,
       63, 27, 67, 60, 44, 61, 23, 42, 34, 33, 32,  1, 35, 55, 64, 69, 37,
       10, 36, 13, 54, 22, 18, 12, 28, 58, 39, 41, 14, 70, 20, 11, 16, 21,
       19, 31, 73,  9, 71, 74, 75, 77, 72, 76], dtype=int64)

In [128]:
ans = []
ans_name = []
for _id in result[:-6]:
    
    f_name = final_name[_id]
    try:
        x = np.where(name == f_name)[0][0]
    except:
        print(f_name, "not found")
    now = [myScore[x], roc[x]]
    ans.append(now)
    ans_name.append(f_name)

rf-7357 not found
rf-7406 not found
vt-7676 not found
rf-7502 not found
rf-7621 not found
rf-7387 not found
lgbm-7639 not found
lgbm-7707 not found
rf-7564 not found
rf-735 not found
svm-7530 not found
rf-7275 not found
lgbm-6719 not found


In [129]:
result = np.array(ans)
x = np.where(result.mean(axis=1) == result.mean(axis=1).max() )
x

(array([66], dtype=int64),)

In [130]:
ans_name[66]

'rf-9286'

In [132]:
result[66]

array([0.92866954, 0.91156738])